### ISSUE TITLE
Max cheat 15 likes in photo?

### ISSUE THREAD

**Issue by bogdanbogaychuk** [ghost1372/Easegram#1]
This program do not work

**Comment by ghost1372** [comment]
hi, its work fine. did you get any error?
connect to VPN or proxy and try again mybe your country blocked servers.
i`m working on this project and i try add some functions that remove some limits. 
let us know if your problem solve or not.

**Comment by bogdanbogaychuk** [comment]
with vpn does not work

2017-04-20 19:12 GMT+03:00 Богдан Богайчук <bgamer.infini@gmail.com>:

**Comment by ghost1372** [comment]
which version do you use?

**Comment by bogdanbogaychuk** [comment]
but it works only turns 200 likes, you can increase the limit to 500? or
more? I will be very grateful

2017-04-21 9:31 GMT+03:00 ghost1372 <notifications@github.com>:

**Comment by ghost1372** [comment]
@bogdanbogaychuk  I've increased the limit from 10 to 20 request. 
Likes are not in our hands.
Likes depends on the traffic servers.
If the servers is busy, the number of likes per request will increase.
You can use two servers to be desired.
also in last release i removed limit for one link! this means you can use one link many times.

**Comment by bogdanbogaychuk** [comment]
Ok, thanks

24 квіт. 2017 р. 17:35 "ghost1372" <notifications@github.com> пише:
