### ISSUE TITLE
Why not work& help

### ISSUE THREAD

**Issue by bogdanbogaychuk** [ghost1372/Easegram#3]
This program not work , swearing is not wound/the program worked then stopped a week ago/ help please&

**Comment by ghost1372** [comment]
hi All of Servers are disabled.
As soon as the new servers are activated, we will update the app.

**Comment by bogdanbogaychuk** [comment]
Thanks, I, m waiting) this app the best

On Jul 1, 2017 18:57, "ghost1372" <notifications@github.com> wrote:

hi All of Servers are disabled.
As soon as the new servers are activated, we will update the app.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ghost1372/Easegram/issues/3#issuecomment-312439947>,
or mute
the thread
