### ISSUE TITLE
Why servers have been shut down for so long. Will they work?

### ISSUE THREAD

**Issue by ghost** [ghost1372/Easegram#5]
Why servers have been shut down for so long. Will they work?

**Comment by ghost1372** [comment]
we dont know, russian disabled servers, we working on to fix server issues

**Comment by ghost1372** [comment]
New Servers Added and App is Active and Work
enjoy!

**Comment by dave-1234** [comment]
Hey Madhi !
I tested the latest version yesterday, it worked fine but then suddenly not anymore. There are no more likes coming in although the app appears to work/load when I click start. Server issues again?
Any idea what could be done to reduce the server issues?

Thank you for your help! Great App !!  
David
