### ISSUE TITLE
Problems Debug help please

### ISSUE THREAD

**Issue by infinityhacker0** [ghost1372/Easegram#6]
![image](https://user-images.githubusercontent.com/30896386/29376310-f55dc754-82d9-11e7-8f9f-8268634604e5.png)

**Comment by ghost1372** [comment]
sorry I forgot to add the UI library, please download new Commit or just download Teen.dll lib from here
https://github.com/ghost1372/Easegram/blob/master/Teen.dll
add to refrences and Rebuild Project, All errors will be fixed

**Comment by infinityhacker0** [comment]
very thanks
