### ISSUE TITLE
No likes at all

### ISSUE THREAD

**Issue by dave-1234** [ghost1372/Easegram#9]
Hey it's me again. After the last time I opened an issue, I figured out that you can only like the most recent picture of a user with your app. Since then it's been working fine, no issues. But since last night there are no more likes coming through. Doesn't matter which account I'm trying. Do you know why and will it work again ?

Thanks again for this great app ! 👍

**Comment by ghost1372** [comment]
hey @dave-1234  welcome back,I tested it right now, It works without problems. you can see it.
<img width="960" alt="untitled" src="https://user-images.githubusercontent.com/9213496/29782808-3514b5a8-8c33-11e7-942e-31b6159ad70c.png">

**Comment by dave-1234** [comment]
Thank you for your quick reply !  I tried it on 2 different systems and it didn't work but then I figured if it works for you, it could be my IP address. Connected to a different network and it was working again!  Slowly but surely we figure this out :)  Thanks for your help 👍
